### ISSUE TITLE
Concepts, Tips, and Tricks

### ISSUE THREAD

**Issue by marcotas** [withfluwy/fluwy#77]
* How to use array styles with YAML to avoid duplicated keys in YAML files
* How to use classes with array styles in components? The implicit "content" components or the short version of components with array content.

### Drafts

In YML you can't have duplicated keys like:

```
column:
  div: ...
  div: ... # <- duplicated key
```

You should do this instead:

```
column:
  - div: ...
  - div: ...
```

The "-" changes it to the array style. And if you want to use `class` with it you should also use the explicit `content` for it: 

```
column:
  class: whatever
  content:
    - div: ...
    - div: ...
```
